apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: catalog
  name: catalog
spec:
  ports:
  - name: "5100"
    port: 80
    targetPort: 80
  selector:
    io.kompose.service: catalog
status:
  loadBalancer: {}
