apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: webmvc
  name: webmvc
spec:
  # For single node clusters, it's probobly best to use NodePort
  type: LoadBalancer
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  selector:
    io.kompose.service: webmvc
status:
  loadBalancer: {}
